#gather_facts: False
- hosts: all
  pre_tasks:
  - name: Install proxyenvironment
    become: yes
    become_user: root
    become_method: sudo
    #raw: test -e /usr/bin/python || ( echo 'http_proxy={{http_proxy}}' >>/etc/environment)
    raw: test -e /usr/bin/python || ( echo 'https_proxy={{https_proxy}}' >>/etc/environment)
    changed_when: False
  - name: Install python for Ansible
    become: yes
    become_user: root
    become_method: sudo
    raw: test -e /usr/bin/python || ( echo 'http_proxy={{http_proxy}}' >>/etc/environment; source . /etc/environment; apt -y update && apt install -y python-minimal)
    changed_when: False
  - setup: # aka gather_facts
